const suffixes: string[] = [
  "yňyzda",
  "yňyz",
  "yň",
  "da",
  "de",
  "lary",
  "leri",
  "ýar",
  "ýan",
  "lar",
  "ler",
  "dan",
  "den",
  "-a",
  "-e",
  "nyň",
  "niň",
  "dy",
  "di",
  "dyr",
  "dir",
  "mak",
  "mek",
  "syz",
  "siz",
  "lyk",
  "lik",
  "ja",
  "je",
  "rak",
  "räk",
  "istan",
  "dar",
  "lygy",
  "ligi",
  "im",
  "imiz",
  "iňiz",
  "si",
  "ýär",
  "er",
  "di",
  "ipdi",
  "se",
  "jek",
  "mekçi",
  "meli",
  "ok",
  "mez",
  "çe",
  "eri",
  "ik",
  "in",
  "uň",
  "üň",
  "ne",
  "nden",
  "nde",
  "mi",
  "my",
  "ka",
  "kä",
  "dir",
  "ir",
  "t",
  "üz",
  "der",
  "il",
  "n",
  "iş",
  "ýän",
  "än",
  "dik",
  "mäge",
  "ip",
  "yş",
  "uş",
  "üş",
  "iş",
  "dym",
  "dim",
  "um",
  "üm",
  "y",
  "i",
  "u",
  "ü",
  "jik",
  "çAçIk",
  "la",
  "dur",
  "d",
  "jIk",
  "çAçIk",
  "LAr",
  "ym",
  "yňyz",
  "iň",
  "lar",
  "dan",
  "den",
  "ynda",
  "inde",
  "unda",
  "ünde",
  "mAK",
  "jIk",
  "çAçIk",
  "lA",
  "ar",
  "ny",
  "ni",
  "dur",
  "dür",
  "lA",
  "bet",
  "jik",
  "çAçIk",
  "nY",
  "nI",
  "dYr",
  "dIr",
  "dUr",
  "dÜr",
  "ar",
  "ler",
  "mAK",
  "jIk",
  "çAçIk",
];

const synonyms: string[][] = [
  ["satyn almak", "almak", "satyn al"],
  ["kredit kart", "bank kart", "plastik kart"],
  ["kitap", "kitaplar", "depter"],
  ["ýol", "ýollar", "ýollar"],
  ["öý", "jaý", "ev"],
  ["adam", "kişi", "erkek"],
  ["gyz", "gyzlar", "gadin"],
  ["suw", "çäý", "syýy"],
  ["gül", "çyçek", "çyçekler"],
  ["at", "ýem", "ot"],
  ["ýaş", "ulug", "uly"],
  ["kiçi", "kiçijik", "ufak"],
  ["gara", "ýaman", "erbet"],
  ["gowy", "ýakşy", "hoş"],
  ["ýolbaşçy", "başlyk", "lider"],
  ["dost", "ýoldaş", "arkadaş"],
  ["iş", "ýumuş", "gul"],
  ["sagat", "wagt", "uakyt"],
  ["ýürek", "gönül", "kalb"],
  ["göz", "gözler", "ňäzir"],
  ["el", "eller", "gol"],
  ["baş", "başlar", "kelle"],
  ["ýer", "ýurt", "toprak"],
  ["söz", "läp", "habar"],
  ["ýagşy", "ýaramaz", "ýarawsyz"],
  ["aý", "ýyldyz", "gün"],
  ["suwuk", "ýumşak", "lyp"],
  ["maşyn", "awto", "awtomobil"],
  ["ýolbars", "pars", "gaplaň"],
  ["akyl", "zihin", "aň"],
  ["howa", "hewa", "gök"],
  ["suwag", "çöl", "ýerasty"],
  ["bilim", "ilim", "okuw"],
  ["sen", "siz"],
  ["şu", "şol"],
  ["şu taýda", "onda", "bäri"],
  ["ol ýerde", "o taýda"],
  ["bary", "hemme", "ähli", "her"],
  ["ynsan", "adam", "kişi"],
  ["it", "köpek", "güýük"],
  ["çöp", "taýak"],
  ["tanap", "ýüp", "urgan"],
  ["deri", "ham"],
  ["saç", "tüý", "gyl"],
  ["baş", "gele"],
  ["aýak"],
  ["pikir etmek", "saýmak", "üýtmek"],
  ["uruşmak", "söweşmek", "göreşmek"],
  ["patlamak", "urmak"],
  ["üflemek", "öwüsmek"],
  ["gum", "çäge"],
  ["çaň", "toz", "tozan"],
  ["gök", "asman"],
  ["köne", "garry"],
  ["erbet", "pis", "ýaman"],
  ["çygly", "öl"],
  ["gurt", "gurçuk"],
  ["bag", "agaç"],
  ["tokaý", "meşe"],
  ["çöp", "taýak"],
  ["miwe", "meywe"],
  ["ýürek", "yürek"],
  ["ýaşamak", "yaşamak"],
  ["suw", "su"],
  ["asman", "gök"],
  ["egsik", "käm"],
  ["agaç", "bag"],
  ["köpek", "it"],
  ["toprak", "ýer"],
  ["kalb", "ýürek"],
  ["yürek", "kalb"],
  ["pis", "erbet"],
  ["öl", "nemli"],
  ["öl", "çygly"],
  ["ot", "otlamak"],
  ["çäý", "çaý"],
  ["ýer", "dünýä"],
  ["at", "ýabany at"],
  ["gök", "semä"],
  ["bilim", "bilgi"],
  ["ilim", "bilim"],
  ["okuw", "öwrenmek"],
  ["dost", "dostluk"],
  ["arkadaş", "dost"],
  ["iş", "işlemek"],
  ["wagt", "sagat"],
  ["kalb", "ýürek"],
  ["göz", "gözgü"],
  ["gol", "el"],
  ["kelle", "baş"],
  ["toprak", "ýer"],
  ["habar", "söz"],
  ["gün", "aý"],
  ["lyp", "suwuk"],
  ["awtomobil", "maşyn"],
  ["gaplaň", "ýolbars"],
  ["aň", "akyl"],
  ["gök", "howa"],
  ["ýerasty", "suwag"],
  ["okuw", "bilim"],
  ["ýagşy", "gowy"],
  ["erbet", "pis", "ýaman"],
  ["çüýrük", "rotten"],
  ["kirli", "hapa", "dirty"],
  ["men", "I"],
  ["sen", "you"],
  ["ol", "he"],
  ["biz", "we"],
  ["siz", "you (pl)"],
  ["olar", "they"],
  ["bu", "this"],
  ["şu", "şol", "that"],
  ["bäri", "here"],
  ["o taýda", "there"],
];

const names: string[] = [
  "Aýgül",
  "Aýperi",
  "Aýzada",
  "Aýsoltan",
  "Aýlar",
  "Aýsenem",
  "Aýjemal",
  "Aýjemile",
  "Aýnur",
  "Aýnabat",
  "Aýnepes",
  "Aýnazar",
  "Aýşöhle",
  "Aýşirin",
  "Aýym",
  "Aýjan",
  "Aýnurana",
  "Aýna",
  "Aýmämmet",
  "Aýdogdy",
  "Akmyrat",
  "Akjemal",
  "Akja",
  "Akbölek",
  "Akbilek",
  "Akpagta",
  "Akperizat",
  "Akşam",
  "Aksoý",
  "Aktoy",
  "Altyn",
  "Altynajy",
  "Altynbike",
  "Altynöri",
  "Altynjan",
  "Alma",
  "Almagül",
  "Almaz",
  "Altynbeg",
  "Annageldi",
  "Annaguly",
  "Annadurdy",
  "Annaberdi",
  "Annamyrat",
  "Annaseýit",
  "Annamämmet",
  "Annaniyaz",
  "Annazar",
  "Arslan",
  "Atageldi",
  "Atamyrat",
  "Atanyýaz",
  "Ata",
  "Ataş",
  "Atajan",
  "Atabay",
  "Atadurdy",
  "Ataberdi",
  "Azat",
  "Aziza",
  "Azize",
  "Azizaý",
  "Azra",
  "Aza",
  "Azhar",
  "Azelya",
  "Azharat",
  "Azamat",
  "Batyr",
  "Baber",
  "Bäşim",
  "Bägül",
  "Bäşimdurdy",
  "Bägülcemal",
  "Begenç",
  "Begli",
  "Begjan",
  "Begzada",
  "Berdi",
  "Berdimurad",
  "Berdimyrat",
  "Berdimuhammet",
  "Berdinazar",
  "Berdinyýaz",
  "Berdy",
  "Berdyýew",
  "Berdyjan",
  "Berdisahet",
  "Berkarar",
  "Berk",
  "Berkeli",
  "Berkjan",
  "Berkdurdy",
  "Berkmyrat",
  "Berkmämmet",
  "Berkserdar",
  "Berkseýt",
  "Berkdaş",
  "Berna",
  "Bibi",
  "Bibinabat",
  "Bibijemal",
  "Bibijan",
  "Bilbil",
  "Bilal",
  "Bilermen",
  "Bolan",
  "Bolduk",
  "Bozoglan",
  "Bozat",
  "Bolat",
  "Böri",
  "Börihan",
  "Bölek",
  "Böritegin",
  "Bölekdurdy",
  "Bölekjan",
  "Böriş",
  "Döwlet",
  "Döwran",
  "Dovran",
  "Döwletgeldi",
  "Döwletmyrat",
  "Döwletmämmet",
  "Döwletguly",
  "Döwletberdi",
  "Durdymyrat",
  "Durdynazar",
  "Durdy",
  "Durdymämmet",
  "Durdyniyaz",
  "Durdynyýaz",
  "Dursun",
  "Dürli",
  "Dürranä",
  "Dürdanä",
  "Dürlihan",
  "Dürjemal",
  "Elmar",
  "Elmira",
  "Elmyrat",
  "Elgün",
  "Elbek",
  "Eligul",
  "Elguly",
  "Elyas",
  "Enejan",
  "Eneli",
  "Enebibi",
  "Enedurdı",
  "Enedurdy",
  "Enedöwlet",
  "Eneş",
  "Erkin",
  "Erkinç",
  "Ersary",
  "Erşat",
  "Ertogrul",
  "Esenguly",
  "Esen",
  "Esenjan",
  "Esenmyrat",
  "Esenmämmet",
  "Esenberdi",
  "Esenazar",
  "Esengeldi",
  "Esenyaz",
  "Esenyurt",
  "Farida",
  "Firuza",
  "Ganym",
  "Ganyş",
  "Gara",
  "Garaş",
  "Garageldi",
  "Garaguly",
  "Garaşsyz",
  "Garagozel",
  "Gaýgysyz",
  "Gazan",
  "Gazageldi",
  "Gazak",
  "Gazallar",
  "Gazygeldi",
  "Gazynazar",
  "Görogly",
  "Gökhan",
  "Gökje",
  "Gökdepe",
  "Gökçä",
  "Gökşan",
  "Gökşirin",
  "Gözel",
  "Güljahan",
  "Güljemal",
  "Güljeren",
  "Gülnabat",
  "Gülnara",
  "Gülruh",
  "Gülşat",
  "Gülşirin",
  "Gülzadä",
  "Gülýaz",
  "Gurban",
  "Gurbangeldi",
  "Gurbanguly",
  "Gurbanmyrat",
  "Gurbanberdi",
  "Gurbanmämmet",
  "Gurbanazar",
  "Gülendam",
  "Gülbahar",
  "Gümrük",
  "Gümrah",
  "Gümüş",
  "Güwher",
  "Guwandyk",
  "Guwanç",
  "Haşim",
  "Hajy",
  "Hajygeldi",
  "Hajymyrat",
  "Hajyguly",
  "Hajyberdi",
  "Hajynazar",
  "Hally",
  "Halykow",
  "Halyguly",
  "Halmyrat",
  "Halnazar",
  "Halmämmet",
  "Halmuhammet",
  "Halmurad",
  "Halyhardy",
  "Halyjan",
  "Hamra",
  "Hamrajan",
  "Hemra",
  "Hemrajan",
  "Hemmät",
  "Hemmehan",
  "Hemraali",
  "Hojamyrat",
  "Hoja",
  "Hojaguly",
  "Hojageldi",
  "Hojamberdi",
  "Hoşgeldi",
  "Hoşmuhammet",
  "Hoşdurdy",
  "Hoşmyrat",
  "Hoşnazar",
  "Hoşsahet",
  "Hudayberdi",
  "Hudaynazar",
  "Hudayguly",
  "Hudaymyrat",
  "Hudaýguly",
  "Hudaýberdi",
  "Hudaýnazar",
  "Hudaýmyrat",
  "Ibrahim",
  "Ilham",
  "Ilmyrat",
  "Ilaman",
  "Ilyas",
  "Işanguly",
  "Işanmyrat",
  "Işan",
  "Jahan",
  "Jahanşah",
  "Jelalet",
  "Jelal",
  "Jemal",
  "Jemile",
  "Jemshyt",
  "Jeren",
  "Jerennaz",
  "Jora",
  "Joraali",
  "Jumaguly",
  "Jumamyrat",
  "Jumanyýaz",
  "Jumanazar",
  "Jumadurdy",
  "Kerim",
  "Kerimguly",
  "Kerimgeldi",
  "Kerimjan",
  "Kerwen",
  "Kerwenli",
  "Kerwenjan",
  "Kezegül",
  "Kemine",
  "Kezel",
  "Kemal",
  "Kemale",
  "Kemalejan",
  "Kamil",
  "Kamiljan",
  "Kamilat",
  "Käbe",
  "Käbi",
  "Kädim",
  "Kädirov",
  "Käkil",
  "Kämyrat",
  "Köpek",
  "Köroğlu",
  "Köşek",
  "Köshe",
  "Köşekgeldi",
  "Köşekmyrat",
  "Köşekguly",
  "Köşeknazar",
  "Kümüş",
  "Kümüşjan",
  "Kümüşgül",
  "Kümüşbike",
  "Lale",
  "Laly",
  "Lalzadä",
  "Leýla",
  "Leýli",
  "Lukman",
  "Magtymguly",
  "Mahym",
  "Mahymgül",
  "Mahri",
  "Mähri",
  "Mähriban",
  "Mährigül",
  "Mahriýa",
  "Mahru",
  "Maksat",
  "Maral",
  "Mansur",
  "Mansurjan",
  "Mansurmyrat",
  "Mansurnazar",
  "Maya",
  "Mälik",
  "Mälikguly",
  "Mälikgulyýew",
  "Mälikjan",
  "Mehri",
  "Mehrişah",
  "Meňli",
  "Meňlihan",
  "Meňlişah",
  "Meret",
  "Mered",
  "Meredmyrat",
  "Meretguly",
  "Merjeme",
  "Merjen",
  "Merdan",
  "Merdanmyrat",
  "Mergen",
  "Mergenjan",
  "Mikail",
  "Mirmyrat",
  "Miras",
  "Mirasa",
  "Mirasberdi",
  "Mirasy",
  "Mizan",
  "Mizangül",
  "Mizanguly",
  "Myahri",
  "Myrat",
  "Myratberdi",
  "Myratdurdy",
  "Myratguly",
  "Myratjan",
  "Myratgeldi",
  "Myratnazar",
  "Myratmyrat",
  "Myratmämmet",
  "Myratmyradow",
  "Myratow",
  "Myratşah",
  "Myratýaz",
  "Myratyk",
  "Myratkerim",
  "Najy",
  "Najyguly",
  "Najyberdi",
  "Najymyrat",
  "Najynazar",
  "Nabat",
  "Nabatgül",
  "Nadežda",
  "Nadira",
  "Nagesh",
  "Nazli",
  "Nazlygül",
  "Nazigül",
  "Nazym",
  "Nazyly",
  "Nazar",
  "Nazarguly",
  "Nazarkuly",
  "Nazarmyrat",
  "Nazarberdi",
  "Nazarmämmet",
  "Nazarbek",
  "Nazarjan",
  "Nazarly",
  "Nesrin",
  "Neslihan",
  "Nesrinjan",
  "Nesibe",
  "Nesrinä",
  "Nesibä",
  "Nejep",
  "Nijat",
  "Nijatguly",
  "Nijatjan",
  "Niyaz",
  "Niyazguly",
  "Niýaz",
  "Niýazguly",
  "Niýazmyrat",
  "Niýazdurdy",
  "Niýazberdi",
  "Niýar",
  "Niýarjan",
  "Nur",
  "Nurana",
  "Nurane",
  "Nurgeldi",
  "Nurgul",
  "Nurgözel",
  "Nurguly",
  "Nuri",
  "Nurmuhammet",
  "Nurmyrat",
  "Nurberdi",
  "Nurberdy",
  "Nurnazar",
  "Nurjemal",
  "Nurjahan",
  "Nurli",
  "Nurmämmet",
  "Nuryagdy",
  "Nuryagdyguly",
  "Nuryagdyberdi",
  "Nuryaz",
  "Nurgun",
  "Nurmukhammet",
  "Ogulabat",
  "Ogulgerek",
  "Oguljemal",
  "Oguljahan",
  "Oguljan",
  "Ogulnabat",
  "Ogulnabatjan",
  "Ogulbahar",
  "Ogulberta",
  "Ogulbibi",
  "Ogulbägül",
  "Ogulruh",
  "Ogulşat",
  "Ogulşirin",
  "Oraz",
  "Orazgeldi",
  "Orazguly",
  "Orazmuhammet",
  "Orazmyrat",
  "Oraznazar",
  "Orazberdi",
  "Orazdurdy",
  "Orazmämmet",
  "Orazhan",
  "Orun",
  "Orunmyrat",
  "Orunjan",
  "Otan",
  "Otajyk",
  "Otamyra",
  "Parahat",
  "Parahatsoltan",
  "Pälewan",
  "Pälwan",
  "Pälwanmyrat",
  "Pälwansoltan",
  "Päygamber",
  "Pälwanberdi",
  "Perhat",
  "Perizat",
  "Peri",
  "Perihan",
  "Perimyrat",
  "Perizad",
  "Rejep",
  "Rejepguly",
  "Rejepgeldi",
  "Rejepmyrat",
];

export const greetings: string[] = [
  "Salam!",
  "Hoş geldiňiz!",
  "Assalamu Aleýkum!",
  "Salam jan dogan!",
  "Günüň haýyrly bolsun!",
  "Eýläp geldiňmi?",
  "Salam hormatly myhman!",
  "Salam, nädip ýagdaýlaryň?",
  "Salam, bagtly gün!",
  "Salam, sag amanmy?",
  "Salawmaleýkim",
  "Waleýkim essalam",
  "Waleýkim",
  "Ertiriňiz haýyrly bolsun",
  "Gündiziňiz haýyrly bolsun",
  "Agşamyňyz haýyrly bolsun",
  "Nähili?",
  "Nähilisiň?",
  "Gowymy?",
  "Gowy, özüň nähili?",
  "Gowy, sagboluň, özüň nähili?",
  "Salawmaleýkim",
  "Agşamyňyz haýyrly bolsun",
  "Yagdaýňyz nähili?",
  "Nähilisiň?",
  "Tanşanymyza şat",
  "Sag bol",
  "Ertiriňiz haýyrly bolsun",
  "Gijäňiz haýyrly bolsun",
  "Hawa",
  "Ýok",
  "Ýaşy",
  "Ýaman",
  "Adyň näme?",
  "Men sizi görüp begenýärin",
  "Men gowy",
  "Yagdaýňyz nähili?",
  "Gowy, sag bol",
  "Salavmaleykim",
  "Nähili?",
  "Yaxshi, sag bol",
  "Adyň näme?",
  "Meň adym [name]",
  "Hoş geldiňiz",
  "Sag boluň",
  "Gowy gün",
  "Salavmaleykim",
  "Salam",
  "Nähili?",
  "Gowy",
  "Erbet",
  "Yagdaýňyz nähili?",
  "Nähilisiň?",
  "Sag bol",
  "Hoş geldiňiz",
  "Assalamu Aleýkum",
  "Waleýkim essalam",
  "Günüň haýyrly bolsun",
  "Agşamyňyz haýyrly bolsun",
  "Ertiriňiz haýyrly bolsun",
  "Gowy gün",
  "Tanşanymyza şat",
  "Men gowy",
];

export const farewells: string[] = [
  "Hoş sag bol!",
  "Görüşýänçä!",
  "Sag aman bol!",
  "Gürrüňdeş bolduk!",
  "Hoş gal!",
  "Özüne gowy seret!",
  "Ýene görüşeris!",
  "Öňüň açyk bolsun!",
  "Salamat boluň!",
  "Geljekde duşuşarys!",
  "Gijäňiz rahat bolsun",
  "Hoş sag boluň",
  "Soňrak duşuşarys",
  "Tiz wagtdan duşuşarys",
  "Ertir duşuşarys",
  "Görüşýänçä",
  "Sag boluň",
  "Hoş boluň",
  "Gijäňiz rahat bolsun",
  "Görüşeris",
  "Hoş sag bol",
  "Sag aman boluň",
  "Özüňe gowy bak",
  "Ýene görüşeliň",
  "Görüşmek üstiňe",
  "Gijäňiz haýyrly bolsun",
  "Hoş boluň",
  "Sag bol",
  "Gijäňiz rahat bolsun",
  "Ýene görüşeris",
  "Sag aman bol",
  "Öňüň açyk bolsun",
  "Hoş sag boluň",
  "Görüşýänçä",
  "Sag boluň",
  "Hoş gal",
  "Gijäňiz rahat bolsun",
  "Ýene görüşeris",
  "Salamat boluň",
];

const conjunctions: { tm: string; translit: string }[] = [
  { tm: "we", translit: "we" },
  { tm: "ýa", translit: "ya" },
  { tm: "ya", translit: "ya" },
  { tm: "emma", translit: "emma" },
  { tm: "şol sebäpden", translit: "shol sebapden" },
  { tm: "şuňa garamazdan", translit: "shuna garamazdan" },
  { tm: "ýogsam", translit: "yogsam" },
  { tm: "eýer", translit: "eyer" },
  { tm: "çünki", translit: "chunki" },
  { tm: "üçin", translit: "uchin" },
  { tm: "hökman", translit: "hokman" },
  { tm: "şonda", translit: "shonda" },
  { tm: "haçan", translit: "hachan" },
  { tm: "nirede", translit: "nirede" },
  { tm: "näme üçin", translit: "name ucin" },
  { tm: "näçe", translit: "nache" },
  { tm: "eýsem", translit: "eysem" },
  { tm: "ýa… ýa", translit: "ya… ya" },
  { tm: "ne… ne", translit: "ne… ne" },
  { tm: "hem… hem", translit: "hem… hem" },
  { tm: "muny bilen birlikde", translit: "muny bilen birlikde" },
  { tm: "ýöne", translit: "yone" },
  { tm: "eyyam", translit: "eyyam" },
  { tm: "eýýäm", translit: "eyyam" },
  { tm: "bilen", translit: "bilen" },
  { tm: "welin", translit: "welin" },
  { tm: "weli", translit: "weli" },
  { tm: "ýöne", translit: "yone" },
  { tm: "da", translit: "da" },
  { tm: "de", translit: "de" },
  { tm: "hem", translit: "hem" },
  { tm: "ýa-da", translit: "ya-da" },
  { tm: "bolsa", translit: "bolsa" },
  { tm: "ýogsam", translit: "yogsam" },
  { tm: "sebäbi", translit: "sebabi" },
  { tm: "şonuň üçin", translit: "shonun ucin" },
  { tm: "ama", translit: "ama" },
  { tm: "fakat", translit: "fakat" },
  { tm: "ancak", translit: "ancak" },
  { tm: "ne", translit: "ne" },
  { tm: "ya-da", translit: "ya-da" },
  { tm: "ise", translit: "ise" },
  { tm: "ile", translit: "ile" },
  { tm: "ki", translit: "ki" },
  { tm: "madem", translit: "madem" },
  { tm: "hatta", translit: "hatta" },
  { tm: "yahut", translit: "yahut" },
];

export { suffixes, synonyms, names, conjunctions };
