interface ElementData {
    atomicNumber: number;
    english: string;
    turkmen: string;
    greek: string;
    latin: string;
    symbol: string;
}

const elements: ElementData[] = [
    { atomicNumber: 1, english: "Hydrogen", turkmen: "Wodorod", greek: "Υδρογόνο (Ydrogóno)", latin: "Hydrogenium", symbol: "H" },
    { atomicNumber: 2, english: "Helium", turkmen: "Geliy", greek: "Ήλιο (Ílio)", latin: "Helium", symbol: "He" },
    { atomicNumber: 3, english: "Lithium", turkmen: "Litiý", greek: "Λίθιο (Líthio)", latin: "Lithium", symbol: "Li" },
    { atomicNumber: 4, english: "Beryllium", turkmen: "Berilliý", greek: "Βηρύλλιο (Virýllio)", latin: "Beryllium", symbol: "Be" },
    { atomicNumber: 5, english: "Boron", turkmen: "Bor", greek: "Βόριο (Vório)", latin: "Borum", symbol: "B" },
    { atomicNumber: 6, english: "Carbon", turkmen: "Uglerod", greek: "Άνθρακας (Ánthrakas)", latin: "Carboneum", symbol: "C" },
    { atomicNumber: 7, english: "Nitrogen", turkmen: "Azot", greek: "Άζωτο (Ázoto)", latin: "Nitrogenium", symbol: "N" },
    { atomicNumber: 8, english: "Oxygen", turkmen: "Kislorod", greek: "Οξυγόνο (Oxygóno)", latin: "Oxygenium", symbol: "O" },
    { atomicNumber: 9, english: "Fluorine", turkmen: "Ftor", greek: "Φθόριο (Fthório)", latin: "Fluorum", symbol: "F" },
    { atomicNumber: 10, english: "Neon", turkmen: "Neon", greek: "Νέον (Néon)", latin: "Neon", symbol: "Ne" },
    { atomicNumber: 11, english: "Sodium", turkmen: "Natriý", greek: "Νάτριο (Nátrio)", latin: "Natrium", symbol: "Na" },
    { atomicNumber: 12, english: "Magnesium", turkmen: "Magnniý", greek: "Μαγνήσιο (Magnísio)", latin: "Magnesium", symbol: "Mg" },
    { atomicNumber: 13, english: "Aluminium", turkmen: "Alyuminiý", greek: "Αλουμίνιο (Aloumínio)", latin: "Aluminium", symbol: "Al" },
    { atomicNumber: 14, english: "Silicon", turkmen: "Kremniý", greek: "Πυρίτιο (Pyrítio)", latin: "Silicium", symbol: "Si" },
    { atomicNumber: 15, english: "Phosphorus", turkmen: "Fosfor", greek: "Φώσφορος (Fósforos)", latin: "Phosphorus", symbol: "P" },
    { atomicNumber: 16, english: "Sulfur", turkmen: "Kükürt", greek: "Θείο (Theío)", latin: "Sulfur", symbol: "S" },
    { atomicNumber: 17, english: "Chlorine", turkmen: "Hlor", greek: "Χλώριο (Chlório)", latin: "Chlorum", symbol: "Cl" },
    { atomicNumber: 18, english: "Argon", turkmen: "Argon", greek: "Αργό (Argó)", latin: "Argon", symbol: "Ar" },
    { atomicNumber: 19, english: "Potassium", turkmen: "Kaliý", greek: "Κάλιο (Kálio)", latin: "Kalium", symbol: "K" },
    { atomicNumber: 20, english: "Calcium", turkmen: "Kalsiý", greek: "Ασβέστιο (Asvéstio)", latin: "Calcium", symbol: "Ca" },
    { atomicNumber: 21, english: "Scandium", turkmen: "Skandiý", greek: "Σκάνδιο (Skándio)", latin: "Scandium", symbol: "Sc" },
    { atomicNumber: 22, english: "Titanium", turkmen: "Titan", greek: "Τιτάνιο (Titánio)", latin: "Titanium", symbol: "Ti" },
    { atomicNumber: 23, english: "Vanadium", turkmen: "Wanadiý", greek: "Βανάδιο (Vanádio)", latin: "Vanadium", symbol: "V" },
    { atomicNumber: 24, english: "Chromium", turkmen: "Hrom", greek: "Χρώμιο (Chrómio)", latin: "Chromium", symbol: "Cr" },
    { atomicNumber: 25, english: "Manganese", turkmen: "Marganes", greek: "Μαγγάνιο (Mangánio)", latin: "Manganum", symbol: "Mn" },
    { atomicNumber: 26, english: "Iron", turkmen: "Demir", greek: "Σίδηρος (Sídiros)", latin: "Ferrum", symbol: "Fe" },
    { atomicNumber: 27, english: "Cobalt", turkmen: "Kobalt", greek: "Κοβάλτιο (Kováltio)", latin: "Cobaltum", symbol: "Co" },
    { atomicNumber: 28, english: "Nickel", turkmen: "Nikel", greek: "Νικέλιο (Nikélio)", latin: "Niccolum", symbol: "Ni" },
    { atomicNumber: 29, english: "Copper", turkmen: "Mis", greek: "Χαλκός (Chalkós)", latin: "Cuprum", symbol: "Cu" },
    { atomicNumber: 30, english: "Zinc", turkmen: "Sink", greek: "Ψευδάργυρος (Psevdárgyros)", latin: "Zincum", symbol: "Zn" },
    { atomicNumber: 31, english: "Gallium", turkmen: "Galliý", greek: "Γάλλιο (Gállio)", latin: "Gallium", symbol: "Ga" },
    { atomicNumber: 32, english: "Germanium", turkmen: "Germaniý", greek: "Γερμάνιο (Germánio)", latin: "Germanium", symbol: "Ge" },
    { atomicNumber: 33, english: "Arsenic", turkmen: "Myşýak", greek: "Αρσενικό (Arsenikó)", latin: "Arsenicum", symbol: "As" },
    { atomicNumber: 34, english: "Selenium", turkmen: "Selen", greek: "Σελήνιο (Selínio)", latin: "Selenium", symbol: "Se" },
    { atomicNumber: 35, english: "Bromine", turkmen: "Brom", greek: "Βρώμιο (Vrómio)", latin: "Bromum", symbol: "Br" },
    { atomicNumber: 36, english: "Krypton", turkmen: "Kripton", greek: "Κρυπτό (Kryptó)", latin: "Krypton", symbol: "Kr" },
    { atomicNumber: 37, english: "Rubidium", turkmen: "Rubidiý", greek: "Ρουβίδιο (Rouvídio)", latin: "Rubidium", symbol: "Rb" },
    { atomicNumber: 38, english: "Strontium", turkmen: "Stronsiý", greek: "Στρόντιο (Stróntio)", latin: "Strontium", symbol: "Sr" },
    { atomicNumber: 39, english: "Yttrium", turkmen: "Ýttriý", greek: "Ύττριο (Ýttrio)", latin: "Yttrium", symbol: "Y" },
    { atomicNumber: 40, english: "Zirconium", turkmen: "Sirkoniý", greek: "Ζιρκόνιο (Zirkónio)", latin: "Zirconium", symbol: "Zr" },
    { atomicNumber: 41, english: "Niobium", turkmen: "Niobiý", greek: "Νιόβιο (Nióvio)", latin: "Niobium", symbol: "Nb" },
    { atomicNumber: 42, english: "Molybdenum", turkmen: "Molibden", greek: "Μολυβδαίνιο (Molyvdaínio)", latin: "Molybdenum", symbol: "Mo" },
    { atomicNumber: 43, english: "Technetium", turkmen: "Tehnesiý", greek: "Τεχνήτιο (Technítio)", latin: "Technetium", symbol: "Tc" },
    { atomicNumber: 44, english: "Ruthenium", turkmen: "Ruteniy", greek: "Ρουθήνιο (Ruthínio)", latin: "Ruthenium", symbol: "Ru" },
    { atomicNumber: 45, english: "Rhodium", turkmen: "Rodiý", greek: "Ρόδιο (Ródio)", latin: "Rhodium", symbol: "Rh" },
    { atomicNumber: 46, english: "Palladium", turkmen: "Palladiý", greek: "Παλλάδιο (Palládio)", latin: "Palladium", symbol: "Pd" },
    { atomicNumber: 47, english: "Silver", turkmen: "Kümüş", greek: "Άργυρος (Árgyros)", latin: "Argentum", symbol: "Ag" },
    { atomicNumber: 48, english: "Cadmium", turkmen: "Kadmiý", greek: "Κάδμιο (Kádmio)", latin: "Cadmium", symbol: "Cd" },
    { atomicNumber: 49, english: "Indium", turkmen: "Indiý", greek: "Ίνδιο (Índio)", latin: "Indium", symbol: "In" },
    { atomicNumber: 50, english: "Tin", turkmen: "Galaýy", greek: "Κασσίτερος (Kassíteros)", latin: "Stannum", symbol: "Sn" },
    { atomicNumber: 51, english: "Antimony", turkmen: "Sürme", greek: "Αντιμόνιο (Antimónio)", latin: "Stibium", symbol: "Sb" },
    { atomicNumber: 52, english: "Tellurium", turkmen: "Tellur", greek: "Τελλούριο (Telloúrio)", latin: "Tellurium", symbol: "Te" },
    { atomicNumber: 53, english: "Iodine", turkmen: "Ýod", greek: "Ιώδιο (Iódio)", latin: "Iodium", symbol: "I" },
    { atomicNumber: 54, english: "Xenon", turkmen: "Ksenon", greek: "Ξένον (Xénon)", latin: "Xenon", symbol: "Xe" },
    { atomicNumber: 55, english: "Caesium", turkmen: "Seziý", greek: "Καίσιο (Kaísio)", latin: "Caesium", symbol: "Cs" },
    { atomicNumber: 56, english: "Barium", turkmen: "Bariý", greek: "Βάριο (Vário)", latin: "Barium", symbol: "Ba" },
    { atomicNumber: 57, english: "Lanthanum", turkmen: "Lantan", greek: "Λανθάνιο (Lanthánio)", latin: "Lanthanum", symbol: "La" },
    { atomicNumber: 58, english: "Cerium", turkmen: "Seriý", greek: "Κήριο (Kírio)", latin: "Cerium", symbol: "Ce" },
    { atomicNumber: 59, english: "Praseodymium", turkmen: "Prazeodimiý", greek: "Πρασεοδύμιο (Praseodýmio)", latin: "Praseodymium", symbol: "Pr" },
    { atomicNumber: 60, english: "Neodymium", turkmen: "Neodimiý", greek: "Νεοδύμιο (Neodýmio)", latin: "Neodymium", symbol: "Nd" },
    { atomicNumber: 61, english: "Promethium", turkmen: "Prometiý", greek: "Προμήθιο (Promíthio)", latin: "Promethium", symbol: "Pm" },
    { atomicNumber: 62, english: "Samarium", turkmen: "Samariý", greek: "Σαμάριο (Samário)", latin: "Samarium", symbol: "Sm" },
    { atomicNumber: 63, english: "Europium", turkmen: "Ýewropiý", greek: "Ευρώπιο (Evrópio)", latin: "Europium", symbol: "Eu" },
    { atomicNumber: 64, english: "Gadolinium", turkmen: "Gadoliniý", greek: "Γαδολίνιο (Gadolínio)", latin: "Gadolinium", symbol: "Gd" },
    { atomicNumber: 65, english: "Terbium", turkmen: "Terbiý", greek: "Τέρβιο (Térvio)", latin: "Terbium", symbol: "Tb" },
    { atomicNumber: 66, english: "Dysprosium", turkmen: "Disproziý", greek: "Δυσπρόσιο (Dyspiósio)", latin: "Dysprosium", symbol: "Dy" },
    { atomicNumber: 67, english: "Holmium", turkmen: "Golmiý", greek: "Όλμιο (Ólmio)", latin: "Holmium", symbol: "Ho" },
    { atomicNumber: 68, english: "Erbium", turkmen: "Erbiý", greek: "Έρβιο (Érvio)", latin: "Erbium", symbol: "Er" },
    { atomicNumber: 69, english: "Thulium", turkmen: "Tuliý", greek: "Θούλιο (Thoúlio)", latin: "Thulium", symbol: "Tm" },
    { atomicNumber: 70, english: "Ytterbium", turkmen: "Ýtterbiý", greek: "Υττέρβιο (Yttérvio)", latin: "Ytterbium", symbol: "Yb" },
    { atomicNumber: 71, english: "Lutetium", turkmen: "Lýutesiý", greek: "Λουτήτιο (Loutítio)", latin: "Lutetium", symbol: "Lu" },
    { atomicNumber: 72, english: "Hafnium", turkmen: "Gafniý", greek: "Χάφνιο (Cháfnio)", latin: "Hafnium", symbol: "Hf" },
    { atomicNumber: 73, english: "Tantalum", turkmen: "Tantal", greek: "Ταντάλιο (Tantálio)", latin: "Tantalum", symbol: "Ta" },
    { atomicNumber: 74, english: "Tungsten", turkmen: "Wolfram", greek: "Βολφράμιο (Volfrámio)", latin: "Wolframium", symbol: "W" },
    { atomicNumber: 75, english: "Rhenium", turkmen: "Reniý", greek: "Ρήνιο (Rínio)", latin: "Rhenium", symbol: "Re" },
    { atomicNumber: 76, english: "Osmium", turkmen: "Osmiý", greek: "Όσμιο (Ósmio)", latin: "Osmium", symbol: "Os" },
    { atomicNumber: 77, english: "Iridium", turkmen: "Iridiy", greek: "Ιρίδιο (Irídio)", latin: "Iridium", symbol: "Ir" },
    { atomicNumber: 78, english: "Platinum", turkmen: "Platina", greek: "Πλατίνα (Platína)", latin: "Platinum", symbol: "Pt" },
    { atomicNumber: 79, english: "Gold", turkmen: "Altyn", greek: "Χρυσός (Chrysós)", latin: "Aurum", symbol: "Au" },
    { atomicNumber: 80, english: "Mercury", turkmen: "Suwuk kümüş", greek: "Υδράργυρος (Ydrárgyros)", latin: "Hydrargyrum", symbol: "Hg" },
    { atomicNumber: 81, english: "Thallium", turkmen: "Talliý", greek: "Θάλλιο (Thállio)", latin: "Thallium", symbol: "Tl" },
    { atomicNumber: 82, english: "Lead", turkmen: "Gurşun", greek: "Μόλυβδος (Mólyvdos)", latin: "Plumbum", symbol: "Pb" },
    { atomicNumber: 83, english: "Bismuth", turkmen: "Wismut", greek: "Βισμούθιο (Vismoúthio)", latin: "Bismuthum", symbol: "Bi" },
    { atomicNumber: 84, english: "Polonium", turkmen: "Poloniý", greek: "Πολώνιο (Polónio)", latin: "Polonium", symbol: "Po" },
    { atomicNumber: 85, english: "Astatine", turkmen: "Astat", greek: "Αστάτιο (Astátio)", latin: "Astatum", symbol: "At" },
    { atomicNumber: 86, english: "Radon", turkmen: "Radon", greek: "Ραδόνιο (Radónio)", latin: "Radon", symbol: "Rn" },
    { atomicNumber: 87, english: "Francium", turkmen: "Fransiý", greek: "Φράνκιο (Fránkio)", latin: "Francium", symbol: "Fr" },
    { atomicNumber: 88, english: "Radium", turkmen: "Radiý", greek: "Ράδιο (Rádio)", latin: "Radium", symbol: "Ra" },
    { atomicNumber: 89, english: "Actinium", turkmen: "Aktiniý", greek: "Ακτίνιο (Aktínio)", latin: "Actinium", symbol: "Ac" },
    { atomicNumber: 90, english: "Thorium", turkmen: "Toriý", greek: "Θόριο (Thório)", latin: "Thorium", symbol: "Th" },
    { atomicNumber: 91, english: "Protactinium", turkmen: "Protaktiniý", greek: "Πρωτακτίνιο (Protaktnío)", latin: "Protactinium", symbol: "Pa" },
    { atomicNumber: 92, english: "Uranium", turkmen: "Uran", greek: "Ουράνιο (Ouránio)", latin: "Uranium", symbol: "U" },
    { atomicNumber: 93, english: "Neptunium", turkmen: "Neptuniý", greek: "Νεπτούνιο (Neptoúnio)", latin: "Neptunium", symbol: "Np" },
    { atomicNumber: 94, english: "Plutonium", turkmen: "Plutoniý", greek: "Πλουτώνιο (Ploutónio)", latin: "Plutonium", symbol: "Pu" },
    { atomicNumber: 95, english: "Americium", turkmen: "Amerisiý", greek: "Αμερίκιο (Ameríkio)", latin: "Americium", symbol: "Am" },
    { atomicNumber: 96, english: "Curium", turkmen: "Kýuriý", greek: "Κούριο (Koúrio)", latin: "Curium", symbol: "Cm" },
    { atomicNumber: 97, english: "Berkelium", turkmen: "Berkeliý", greek: "Μπερκέλιο (Berkélio)", latin: "Berkelium", symbol: "Bk" },
    { atomicNumber: 98, english: "Californium", turkmen: "Kaliforniý", greek: "Καλιφόρνιο (Kalifórnio)", latin: "Californium", symbol: "Cf" },
    { atomicNumber: 99, english: "Einsteinium", turkmen: "Éýnşteýniý", greek: "Αϊνστάνιο (Aïnstánio)", latin: "Einsteinium", symbol: "Es" },
    { atomicNumber: 100, english: "Fermium", turkmen: "Fermiý", greek: "Φέρμιο (Férmio)", latin: "Fermium", symbol: "Fm" },
    { atomicNumber: 101, english: "Mendelevium", turkmen: "Mendelewiý", greek: "Μεντελέβιο (Mendelévio)", latin: "Mendelevium", symbol: "Md" },
    { atomicNumber: 102, english: "Nobelium", turkmen: "Nobeliý", greek: "Νομπέλιο (Nompélio)", latin: "Nobelium", symbol: "No" },
    { atomicNumber: 103, english: "Lawrencium", turkmen: "Lawrensiý", greek: "Λωρένσιο (Lorénsio)", latin: "Lawrencium", symbol: "Lr" },
    { atomicNumber: 104, english: "Rutherfordium", turkmen: "Ruterfordiý", greek: "Ραδερφόρντιο (Raderfórntio)", latin: "Rutherfordium", symbol: "Rf" },
    { atomicNumber: 105, english: "Dubnium", turkmen: "Dubniý", greek: "Ντούμπνιο (Doúmpnio)", latin: "Dubnium", symbol: "Db" },
    { atomicNumber: 106, english: "Seaborgium", turkmen: "Seaborgiý", greek: "Σιμπόργιο (Simpórgio)", latin: "Seaborgium", symbol: "Sg" },
    { atomicNumber: 107, english: "Bohrium", turkmen: "Boriý", greek: "Μπόριο (Bório)", latin: "Bohrium", symbol: "Bh" },
    { atomicNumber: 108, english: "Hassium", turkmen: "Gassiý", greek: "Χάσσιο (Chássio)", latin: "Hassium", symbol: "Hs" },
    { atomicNumber: 109, english: "Meitnerium", turkmen: "Meýtneriý", greek: "Μαϊτνέριο (Maïtnério)", latin: "Meitnerium", symbol: "Mt" },
    { atomicNumber: 110, english: "Darmstadtium", turkmen: "Darmştadtiý", greek: "Νταρμστάντιο (Ntarmstántio)", latin: "Darmstadtium", symbol: "Ds" },
    { atomicNumber: 111, english: "Roentgenium", turkmen: "Röntgeniý", greek: "Ρέντγκενιο (Réntgkenio)", latin: "Roentgenium", symbol: "Rg" },
    { atomicNumber: 112, english: "Copernicium", turkmen: "Kopernisiý", greek: "Κοπερνίκιο (Koperníkio)", latin: "Copernicium", symbol: "Cn" },
    { atomicNumber: 113, english: "Nihonium", turkmen: "Nihoniý", greek: "Νιχόνιο (Nichónio)", latin: "Nihonium", symbol: "Nh" },
    { atomicNumber: 114, english: "Flerovium", turkmen: "Flerowiý", greek: "Φλερόβιο (Fleróvio)", latin: "Flerovium", symbol: "Fl" },
    { atomicNumber: 115, english: "Moscovium", turkmen: "Moskowiý", greek: "Μοσκόβιο (Moskovio)", latin: "Moscovium", symbol: "Mc" },
    { atomicNumber: 116, english: "Livermorium", turkmen: "Liwermoriý", greek: "Λιβερμόριο (Livermório)", latin: "Livermorium", symbol: "Lv" },
    { atomicNumber: 117, english: "Tennessine", turkmen: "Tennessin", greek: "Τεννεσσίνιο (Tenessínio)", latin: "Tennessinum", symbol: "Ts" },
    { atomicNumber: 118, english: "Oganesson", turkmen: "Oganesson", greek: "Ογκανεσσόνιο (Oganessonío)", latin: "Oganesson", symbol: "Og" }
];

export default elements;